### ISSUE TITLE
Cannot call function csrfField

### ISSUE THREAD

**Issue by edDimensi** [poppinss/edge#17]
partials/popups.edge
```
@!component('components/modalLogin')
```
components/modalLogin
```
<form>
{{ csrfField() }}
</form>
```
Error
```
[1] { Error: Cannot call function csrfField from components/modalLogin.edge view
[1]     at Context.callFn (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Context/index.js:286:13)
[1]     at Template.templateFn (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:9:52)
[1]     at Template.eval (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:29:14)
[1]     at TemplateRunner.run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:54:39)
[1]     at Template.renderWithContext (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/index.js:445:55)
[1]     at Template.isolate.bind.newContext.$slot.main (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:51:20)
[1]     at Template.isolate (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/index.js:398:5)
[1]     at Template.templateFn (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:50:8)
[1]     at Template.eval (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:81:14)
[1]     at TemplateRunner.run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:54:39)
[1]     at Template.runTimeRender (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/index.js:374:65)
[1]     at Template.templateFn (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:4:18)
[1]     at Template.eval (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:12:14)
[1]     at TemplateRunner.run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:54:39)
[1]     at Template.runTimeRender (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/index.js:374:65)
[1]     at Template.templateFn (eval at run (/home/dimensi/projects/paraspace/node_modules/edge.js/src/Template/Runner.js:51:20), <anonymous>:24:18) status: 500 }
```

**Comment by thetutlage** [comment]
Components state is isolated, so you will have to pass the csrfField method to it from your parent template 

```
@!component(‘name’, csrfField = csrfField)
```

**Comment by RomainLanz** [comment]
Hey @edDimensi! 👋 

According to the name of your component if think you should use partials instead of a component.

Components are created to be reused (like, `Button`, `Modal`, `MenuItem`, ...) and a state + slots are sent to them to change how they behave.

**Comment by edDimensi** [comment]
Hm, but i see issue https://github.com/poppinss/edge/issues/2 and csrfField it's global helper, not?

**Comment by thetutlage** [comment]
It's a local variable share for each request, since the value of `csrfField` has to be different for each HTTP request.
